/**
 * Which picture to show for a part, and where a new one is kept.
 *
 * The owner's own photo always wins. Failing that, the part's Website Catalog picture — but only
 * one the owner has published. A catalog picture may have been generated by AI from a reference
 * photo, and the data does not say which; publishing it is the one sign that the owner approved it
 * as what the part looks like. A picture nobody signed off on is not shown as the part.
 */

export type PhotoSource = 'own' | 'catalog';
export type PartPhotoRef = { url: string; source: PhotoSource };

export type CatalogPhotoRow = {
  erp_product_id?: unknown;
  image_url?: unknown;
  image_status?: unknown;
  publication_status?: unknown;
  updated_at?: unknown;
};

const text = (value: unknown) => (typeof value === 'string' ? value.trim() : '');

/** Part id → the published catalog picture for it. Where one part somehow has two, the most
 *  recently updated wins. */
export function catalogPhotoIndex(rows: CatalogPhotoRow[]): Map<string, string> {
  const best = new Map<string, { url: string; at: string }>();
  for (const row of rows) {
    const productId = text(row.erp_product_id);
    const url = text(row.image_url);
    if (!productId || !url) continue;
    if (text(row.image_status) !== 'ready' || text(row.publication_status) !== 'published') continue;
    const at = text(row.updated_at);
    const current = best.get(productId);
    if (!current || at > current.at) best.set(productId, { url, at });
  }
  return new Map([...best].map(([productId, { url }]) => [productId, url]));
}

export function photoOf(product: { id: string; image_url?: string | null }, catalog: Map<string, string>): PartPhotoRef | null {
  const own = text(product.image_url);
  if (own) return { url: own, source: 'own' };
  const fromCatalog = catalog.get(product.id);
  return fromCatalog ? { url: fromCatalog, source: 'catalog' } : null;
}

/** Photos of parts live in the catalog's public bucket, under their own folder so nothing that
 *  manages catalog pictures ever touches them, and the reverse. */
export const PART_PHOTO_PREFIX = 'part-photos';

const EXTENSIONS: Record<string, string> = { 'image/jpeg': 'jpg', 'image/png': 'png', 'image/webp': 'webp' };

/** A new name for every upload, so a browser that cached the old photo never keeps showing it. */
export function partPhotoPath(companyId: string, productId: string, mimeType: string, stamp: number): string {
  const safe = (value: string) => value.replace(/[^A-Za-z0-9_-]/g, '');
  const ext = EXTENSIONS[mimeType] ?? 'jpg';
  return `${PART_PHOTO_PREFIX}/${safe(companyId)}/${safe(productId)}-${stamp}.${ext}`;
}

/** The storage path of a photo this feature stored, or null for any other URL — so replacing or
 *  removing a part's photo can tidy up its own file and can never delete a catalog picture. */
export function ownPhotoPath(url: string | null | undefined): string | null {
  const value = text(url);
  const marker = `/${PART_PHOTO_PREFIX}/`;
  const at = value.indexOf(marker);
  return at < 0 ? null : value.slice(at + 1).split('?')[0];
}
